c_compiler:
  - vs2010  # [win]
cxx_compiler:
  - vs2010  # [win]
zip_keys:
  -
    - python
    - vc  # [win]
    - c_compiler  # [win]
    - cxx_compiler  # [win]
pin_run_as_build:
  vc:
    max_pin: x
python:
  - 3.4
vc:  # [win]
  - 10  # [win]