{% set version = "2.13.2" %}

package:
  name: freetype
  version: {{ version }}

source:
  url: https://download.savannah.gnu.org/releases/freetype/freetype-{{ version }}.tar.gz
  sha256: 1ac27e16c134a7f2ccea177faba19801131116fd682efc1f5737037c5db224b5
  patches:
    - CVE-2022-37434.patch

build:
  number: 0
  run_exports:
    # has removed symbols at minor versions, but only very rarely.  Go with major.
    #  https://abi-laboratory.pro/tracker/timeline/freetype/
    - {{ pin_subpackage('freetype') }}

requirements:
  build:
    - libtool  # [unix]
    - {{ compiler('c') }}
    - cmake  # [win]
    - make  # [not win]
    - ninja  # [win]
  host:
    - libpng
    - zlib

test:
  commands:
    - ${PREFIX}/bin/freetype-config --version  # [not win]
    - if exist %LIBRARY_BIN%\freetype.dll (exit 0) else (exit 1)  # [win]

about:
  home: https://www.freetype.org/
  license: GPL-2.0-only OR FTL
  license_file:
    - docs/GPLv2.TXT
    - docs/FTL.TXT
  summary: A Free, High-Quality, and Portable Font Engine
  description: |
    FreeType is designed to be small, efficient, highly customizable
    and portable while capable of producing high-quality output (glyph images)
    of most vector and bitmap font formats.
  doc_url: http://freetype.sourceforge.net/freetype2/documentation.html
  doc_source_url: https://sourceforge.net/projects/freetype/?source=navbar
  dev_url: http://git.savannah.gnu.org/cgit/freetype/

extra:
  recipe-maintainers:
    - ccordoba12
    - msarahan
    - ocefpaf
