{% set version = "2.13.0" %}
{% set major, minor, patch = version.split(".") %}

package:
  name: freetype
  version: {{ version }}

source:
  git_url: https://github.com/freetype/freetype
  git_tag: VER-{{ major }}-{{ minor }}-{{ patch }}
  # url: https://github.com/freetype/freetype/archive/refs/tags/VER-{{ major }}-{{ minor }}-{{ patch }}.tar.gz
  # sha256: a683f1091aee95d2deaca9292d976f87415610b8ae1ea186abeebcb08e83ab12

build:
  number: 0
  run_exports:
    # has removed symbols at minor versions, but only very rarely.  Go with major.
    #  https://abi-laboratory.pro/tracker/timeline/freetype/
    - {{ pin_subpackage('freetype') }}

requirements:
  build:
    - {{ compiler('c') }}
    - autoconf  # [not win]
    - automake  # [not win]
    - cmake  # [win]
    - libtool  # [not win]
    - make  # [not win]
    - ninja  # [win]
    - git  # [not win]
  host:
    - libpng
    - zlib

test:
  commands:
    - ${PREFIX}/bin/freetype-config --version  # [not win]
    - if exist %LIBRARY_BIN%\freetype.dll (exit 0) else (exit 1)  # [win]

about:
  home: https://www.freetype.org/
  license: GPL-2.0-only and LicenseRef-FreeType
  license_file:
    - docs/GPLv2.TXT
    - docs/FTL.TXT
  summary: A Free, High-Quality, and Portable Font Engine
  description: |
    FreeType is designed to be small, efficient, highly customizable
    and portable while capable of producing high-quality output (glyph images)
    of most vector and bitmap font formats.
  doc_url: http://freetype.sourceforge.net/freetype2/documentation.html
  doc_source_url: https://sourceforge.net/projects/freetype/?source=navbar
  dev_url: http://git.savannah.gnu.org/cgit/freetype/

extra:
  recipe-maintainers:
    - ccordoba12
    - msarahan
    - ocefpaf
