appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {linux_aarch64: azure, linux_ppc64le: azure, win: azure}
travis:
  secure: {BINSTAR_TOKEN: i8jovpInkPWwTythEPUi+K/n3lSEbhyURpvINBzWEtQnH80PMtTex0Y2le5hL1BT9L31K394MZER2cSEmrLNGeBVyPS94Pl+QoTDMm6FKCH4PmpcL3tkaNFBesqG7T7yUHXRamrUbqPBGTVSoQ6HcqM+phU6nXv5c3dk+LB65/lW2YUEpeWT4NPOnY2pTUBthKxc4Vu5oVC0yRHdVmH6xkhHjTbHquX5oBKwg+kq3x0bVj8zlSd7P6SCaC1aFnSwp7RzcMtoJ3Kdg7qXecVA8ERDOibx12bPzFatgY5UpnMsGQqgoDWpadq5L0EzYZlGBehp3NLQxnAD/nRre2iLfb3HhAAGoZKtZKOhuCcNeNTcLkg2M4WAYEEA5qgRRg7DChrDrr5gE99znLNih/1+cOEdIntt5NKCUvXYMfMSVU/r7hxb5CdKUMpcBDf2P8oDtrLCwDCP4NXgUXXxl//wHzbWjX3xGOORZAs9tvmQ3nU59sffG5fM3OPGwNtg3dQvkEQkxl0I9448TqV0kkJ7ulNHazJ/ha8U0Gfibkp5IS3P1zqLUeCFuU9ZJOAsxT+0PbBVHquKR7T/g4OjVHBSwz+FUSVVkPuZGp95wuKgJyH2rWHXjx5zLHqBfm/tIPat+mdm06xipzdCB41tXZRW6SYnP1Et7OrZaz23gVUy98Y=}
